apiVersion: v1
kind: ConfigMap
metadata:
  name: USER_NAME
  namespace: NAME_SPACE
data:
  config: | 
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data:
        server: https://IP_ADDR:6443
      name: kubernetes
    contexts:
    - context:
        cluster: kubernetes
        user: kubernetes-admin
        namespace: NAME_SPACE
      name: NAME_SPACE
    current-context: NAME_SPACE
    kind: Config
    preferences: {}
    users:
    - name: kubernetes-admin
      user:
        client-certificate-data:
        client-key-data:
