apiVersion: v1
kind: Secret
metadata:
  name: mariadb-cluster
  namespace: NAME_SPACE
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: mariadb-cluster
type: Opaque
data:
  mariadb-root-password: "MARIA_DB_ROOT_PWD"
  mariadb-password: "MARIA_DB_PWD"
  mariadb-replication-password: "MARIA_DB_REPLICATION_PWD"
