apiVersion: v1
kind: Secret
metadata:
  name: mariadb-cluster
  namespace: NAME_SPACE
  labels:
    app.kubernetes.io/name: mariadb
    helm.sh/chart: mariadb-9.3.2
    app.kubernetes.io/instance: mariadb-cluster
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  mariadb-root-password: "MARIA_DB_ROOT_PWD"
  mariadb-password: "MARIADB_PWD"
  mariadb-replication-password: "MARIADB_REPLICATION_PWD"
