apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-nfs-provisioner
  labels:
    app: nfs-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-provisioner
      release: nfs
  template:
    metadata:
      annotations:
      labels:
        app: nfs-provisioner
        release: nfs
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
                - key: dev-pjt-master
                  operator: In
                  values:
                    - "true"
      serviceAccountName: nfs-nfs-provisioner
      containers:
        - name: nfs-provisioner
          image: "quay.io/external_storage/nfs-client-provisioner:v3.1.0-k8s1.11"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: nfs-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: cluster.local/nfs-client-nfs-client-provisioner
            - name: NFS_SERVER
              value: {nfs_server}
            - name: NFS_PATH
              value: {nfs_path}
      volumes:
        - name: nfs-root
          nfs:
            server: {nfs_server}
            path: {nfs_path}
