apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: CLASS_NAME
  labels:
    app: nfs-provisioner
provisioner: cluster.local/nfs-client-nfs-client-provisioner
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  archiveOnDelete: "true"
